#!/bin/bash
echo "script-input"
echo "\$* value is $*"
echo "\$@ value is $@"
echo "\$n value is $n"
echo "\$# value is $#"
echo "\$$ value is $$"
echo "\$! value is $!"
echo "\$1 value is $1"
echo "\$2 value is $2"
echo "\$3 value is $3"
echo "\$4 value is $4"
echo "\$5 value is $5"
echo "\$6 value is $6"
echo "\$7 value is $7"
echo "\$8 value is $8"
echo "\$9 value is $9"
